### ISSUE TITLE
Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/posdao-test-setup#66]
```
MacBook-Pro-Viktor-2:posdao-test-setup viktor$ node -v
v10.19.0
MacBook-Pro-Viktor-2:posdao-test-setup viktor$ npm -v
6.13.4
```

NPM dependencies successfully installed with `npm i`

Launching of `npm run all` causes this error:
```
**** Check that StakingToken is already deployed in StakingAuRa
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/web3-providers-http/src/index.js:92:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/web3-providers-http/src/index.js:92:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

/Users/viktor/Documents/POANetwork/posdao-test-setup/node_modules/solc/soljson.js:31
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__I_000101=Module["__GLOBAL__I_000101"]=asm["__GLOBAL__I_000101"];var __GLOBAL__sub_I_ABIFunctions_cpp=Module["__GLOBAL__sub_I_ABIFunctions_cpp"]=asm["__GLOBAL__sub_I_ABIFunctions_cpp"];var __GLOBAL__sub_I_ABI_cpp=Module["__GLOBAL__sub_I_ABI_cpp"]=asm["__GLOBAL__sub_I_ABI_cpp"];var __GLOBAL__sub_I_ASTJsonConverter_cpp=Module["__GLOBAL__sub_I_ASTJsonConverter_cpp"]=asm["__GLOBAL__sub_I_ASTJsonConverter_cpp"];var __GLOBAL__sub_I_AST_cpp=Module["__GLOBAL__sub_I_AST_cpp"]=asm["__GLOBAL__sub_I_AST_cpp"];var __GLOBAL__sub_I_ArrayUtils_cpp=Module["__GLOBAL__sub_I_ArrayUtils_cpp"]=asm["__GLOBAL__sub_I_ArrayUtils_cpp"];var __GLOBAL__sub_I_AsmAnalysis_cpp=Module["__GLOBAL__sub_I_AsmAnalysis_cpp"]=asm["__GLOBAL__sub_I_AsmAnalysis_cpp"];var __GLOBAL__sub_I_CompilerContext_cpp=Module["__GLOBAL__sub_I_CompilerContext_cpp"]=asm["__GLOBAL__sub_I_CompilerContext_cpp"];var __GLOBA
abort({}). Build with -s ASSERTIONS=1 for more info.
```

**Comment by varasev** [comment]
@vbaranov Could you try this once more? I can't reproduce this, tried on Ubuntu and Mac.

**Comment by vbaranov** [comment]
I can't reproduce this issue anymore on a fresh install
